---
- name: Delete default nginx config directory
  file:
    path: /etc/nginx/sites-available
    state: absent
 
- name: Delete default nginx config directory
  file:
    path: /etc/nginx/sites-enabled
    state: absent

- name: Apply nginx config template for selected SSL type
  template:
    src: "nginx/{{ SSL_type }}-mattermost.conf.j2"
    dest: /etc/nginx/conf.d/mattermost.conf
  notify: restart nginx

- include_tasks: "SSL/{{ SSL_type }}.yml"
  when: SSL_type != "nossl"
# vim:ft=ansible
